CREATE TABLE PRODUCT (
    PRODUCT_ID INT,
    NAME VARCHAR(255),
    PRICE DECIMAL(10,2)
);
CREATE TABLE INVENTORY (
    PRODUCT_ID INT,
    STORE_ID INT,
    QUANTITY INT
);

SELECT *
FROM PRODUCT P
LEFT JOIN INVENTORY I
ON P.PRODUCT_ID = I.PRODUCT_ID;


SELECT *
FROM PRODUCT P
RIGHT JOIN INVENTORY I
ON P.PRODUCT_ID = I.PRODUCT_ID;


SELECT *
FROM PRODUCT P
INNER JOIN INVENTORY I
ON P.PRODUCT_ID = I.PRODUCT_ID;


SELECT *
FROM PRODUCT P
LEFT JOIN INVENTORY I
ON P.PRODUCT_ID = I.PRODUCT_ID
WHERE I.PRODUCT_ID IS NULL;


SELECT *
FROM PRODUCT P
RIGHT JOIN INVENTORY I
ON P.PRODUCT_ID = I.PRODUCT_ID
WHERE P.PRODUCT_ID IS NULL;